apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
type: Opaque
data:
  db-user: bWxvcHM=
  db-password: cFByVDMzR2g5aGRMRWNMNEdWMjk= # pPrT33Gh9hdLEcL4GV29
  # 在shell中对base64进行解码
  # echo "secret" | base64 -d